interface TechStackItem {
  category: string;
  name: string;
}

export const TECH_STACKS: TechStackItem[] = [
  // Frontend (Web)
  { category: 'Frontend', name: 'JavaScript' },
  { category: 'Frontend', name: 'TypeScript' },
  { category: 'Frontend', name: 'HTML5 / CSS3' },
  { category: 'Frontend', name: 'React' },
  { category: 'Frontend', name: 'Next.js' },
  { category: 'Frontend', name: 'Vue.js' },
  { category: 'Frontend', name: 'Nuxt' },
  { category: 'Frontend', name: 'Svelte' },
  { category: 'Frontend', name: 'SvelteKit' },
  { category: 'Frontend', name: 'Angular' },
  { category: 'Frontend', name: 'Qwik' },
  { category: 'Frontend', name: 'Astro' },
  { category: 'Frontend', name: 'Remix' },
  { category: 'Frontend', name: 'JQuery' },
  { category: 'Frontend', name: 'Electron' },
  { category: 'Frontend', name: 'Tauri' },
  { category: 'Frontend', name: 'Redux / Redux Toolkit' },
  { category: 'Frontend', name: 'Recoil' },
  { category: 'Frontend', name: 'Zustand' },
  { category: 'Frontend', name: 'Jotai' },
  { category: 'Frontend', name: 'MobX' },
  { category: 'Frontend', name: 'TanStack Query' },
  { category: 'Frontend', name: 'SWR' },
  { category: 'Frontend', name: 'Tailwind CSS' },
  { category: 'Frontend', name: 'styled-components' },
  { category: 'Frontend', name: 'Emotion' },
  { category: 'Frontend', name: 'Sass/SCSS' },
  { category: 'Frontend', name: 'Vanilla Extract' },
  { category: 'Frontend', name: 'Bootstrap' },
  { category: 'Frontend', name: 'MUI' },
  { category: 'Frontend', name: 'Chakra UI' },
  { category: 'Frontend', name: 'Ant Design' },
  { category: 'Frontend', name: 'Shadcn/ui' },

  // Mobile
  { category: 'Mobile', name: 'React Native' },
  { category: 'Mobile', name: 'Flutter' },
  { category: 'Mobile', name: 'Swift / SwiftUI' },
  { category: 'Mobile', name: 'Kotlin / Jetpack Compose' },
  { category: 'Mobile', name: 'Expo' },

  // Backend
  { category: 'Backend', name: 'Node.js' },
  { category: 'Backend', name: 'Java' },
  { category: 'Backend', name: 'Python' },
  { category: 'Backend', name: 'Kotlin' },
  { category: 'Backend', name: 'Go' },
  { category: 'Backend', name: 'Rust' },
  { category: 'Backend', name: 'C#' },
  { category: 'Backend', name: 'PHP' },
  { category: 'Backend', name: 'Ruby' },
  { category: 'Backend', name: 'Scala' },
  { category: 'Backend', name: 'Elixir' },
  { category: 'Backend', name: 'NestJS' },
  { category: 'Backend', name: 'Express.js' },
  { category: 'Backend', name: 'Fastify' },
  { category: 'Backend', name: 'Spring Boot' },
  { category: 'Backend', name: 'FastAPI' },
  { category: 'Backend', name: 'Django' },
  { category: 'Backend', name: 'Flask' },
  { category: 'Backend', name: 'Gin' },
  { category: 'Backend', name: 'Ruby on Rails' },
  { category: 'Backend', name: 'Laravel' },
  { category: 'Backend', name: 'ASP.NET Core' },
  { category: 'Backend', name: 'Prisma' },
  { category: 'Backend', name: 'TypeORM' },
  { category: 'Backend', name: 'Sequelize' },
  { category: 'Backend', name: 'Drizzle ORM' },
  { category: 'Backend', name: 'JPA / Hibernate' },
  { category: 'Backend', name: 'Mongoose' },
  { category: 'Backend', name: 'MyBatis' },

  // Data
  { category: 'Data', name: 'MySQL' },
  { category: 'Data', name: 'PostgreSQL' },
  { category: 'Data', name: 'MariaDB' },
  { category: 'Data', name: 'Oracle' },
  { category: 'Data', name: 'MSSQL' },
  { category: 'Data', name: 'SQLite' },
  { category: 'Data', name: 'MongoDB' },
  { category: 'Data', name: 'Redis' },
  { category: 'Data', name: 'DynamoDB' },
  { category: 'Data', name: 'Firestore' },
  { category: 'Data', name: 'Cassandra' },
  { category: 'Data', name: 'Elasticsearch' },
  { category: 'Data', name: 'Firebase' },
  { category: 'Data', name: 'Supabase' },
  { category: 'Data', name: 'PocketBase' },
  { category: 'Data', name: 'Appwrite' },
  { category: 'Data', name: 'Kafka' },
  { category: 'Data', name: 'RabbitMQ' },

  // Infrastructure (Cloud, DevOps, CI/CD)
  { category: 'Infrastructure', name: 'NCP' },
  { category: 'Infrastructure', name: 'AWS' },
  { category: 'Infrastructure', name: 'GCP' },
  { category: 'Infrastructure', name: 'Azure' },
  { category: 'Infrastructure', name: 'Vercel' },
  { category: 'Infrastructure', name: 'Netlify' },
  { category: 'Infrastructure', name: 'Heroku' },
  { category: 'Infrastructure', name: 'Railway' },
  { category: 'Infrastructure', name: 'Fly.io' },
  { category: 'Infrastructure', name: 'Cloudflare Workers' },
  { category: 'Infrastructure', name: 'Docker' },
  { category: 'Infrastructure', name: 'Kubernetes' },
  { category: 'Infrastructure', name: 'Jenkins' },
  { category: 'Infrastructure', name: 'GitHub Actions' },
  { category: 'Infrastructure', name: 'GitLab CI' },
  { category: 'Infrastructure', name: 'Terraform' },
  { category: 'Infrastructure', name: 'Ansible' },
  { category: 'Infrastructure', name: 'Nginx' },

  // Collaboration
  { category: 'Collaboration', name: 'Figma' },
  { category: 'Collaboration', name: 'Adobe XD' },
  { category: 'Collaboration', name: 'Zeplin' },
  { category: 'Collaboration', name: 'Sketch' },
  { category: 'Collaboration', name: 'Photoshop / Illustrator' },
  { category: 'Collaboration', name: 'Slack' },
  { category: 'Collaboration', name: 'Discord' },
  { category: 'Collaboration', name: 'Notion' },
  { category: 'Collaboration', name: 'Jira' },
  { category: 'Collaboration', name: 'Trello' },
  { category: 'Collaboration', name: 'Linear' },
  { category: 'Collaboration', name: 'Asana' },
  { category: 'Collaboration', name: 'Confluence' },
  { category: 'Collaboration', name: 'Git' },
  { category: 'Collaboration', name: 'GitHub' },
  { category: 'Collaboration', name: 'GitLab' },
  { category: 'Collaboration', name: 'Bitbucket' },
];

// 예외 처리가 필요한 이름들을 매핑(Simple Icons 슬러그 기준)
export const iconMap: Record<string, string> = {
  'React Native': 'react',
  'C#': 'csharp',
  'Express.js': 'express',
  GCP: 'googlecloud',
  NCP: 'naver',
  'Photoshop / Illustrator': 'adobephotoshop',
  'styled-components': 'styledcomponents',
  SvelteKit: 'svelte',
  'TanStack Query': 'tanstack',
  'Shadcn/ui': 'shadcnui',
  'Drizzle ORM': 'drizzle',
  Cassandra: 'apachecassandra',
  'JPA / Hibernate': 'hibernate',
  MyBatis: 'mybatis',
  Kafka: 'kafka',
  'GitLab CI': 'gitlab',
};
